In [2]:
from biopandas.pdb import PandasPdb

# Initialize a new PandasPdb object
# and fetch the PDB file from rcsb.org
ppdb = PandasPdb().fetch_pdb('3eiy')

print('PDB Code: %s' % ppdb.code)
print('PDB Header Line: %s' % ppdb.header)
print('\nRaw PDB file contents:\n\n%s\n...' % ppdb.pdb_text[:1000])

PDB Code:
PDB Header Line:

Raw PDB file contents:

HEADER    HYDROLASE                               17-SEP-08   3EIY
TITLE     CRYSTAL STRUCTURE OF INORGANIC PYROPHOSPHATASE FROM BURKHOLDERIA
TITLE    2 PSEUDOMALLEI WITH BOUND PYROPHOSPHATE
COMPND    MOL_ID: 1;
COMPND   2 MOLECULE: INORGANIC PYROPHOSPHATASE;
COMPND   3 CHAIN: A;
COMPND   4 EC: 3.6.1.1;
COMPND   5 ENGINEERED: YES
SOURCE    MOL_ID: 1;
SOURCE   2 ORGANISM_SCIENTIFIC: BURKHOLDERIA PSEUDOMALLEI 1710B;
SOURCE   3 ORGANISM_TAXID: 320372;
SOURCE   4 GENE: PPA, BURPS1710B_1237;
SOURCE   5 EXPRESSION_SYSTEM
...

In [5]:
ppdb.df['ATOM'].head(25)

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,SER,,A,2,,...,2.527,54.656,-1.667,1.0,52.73,,,N,NaN,609
1,ATOM,2,,CA,,SER,,A,2,,...,3.259,54.783,-0.368,1.0,52.54,,,C,NaN,610
2,ATOM,3,,C,,SER,,A,2,,...,4.127,53.553,-0.105,1.0,52.03,,,C,NaN,611
3,ATOM,4,,O,,SER,,A,2,,...,5.274,53.451,-0.594,1.0,52.45,,,O,NaN,612
4,ATOM,5,,CB,,SER,,A,2,,...,2.273,54.944,0.792,1.0,52.69,,,C,NaN,613
5,ATOM,6,,OG,,SER,,A,2,,...,2.066,56.306,1.121,1.0,54.37,,,O,NaN,614
6,ATOM,7,,N,,PHE,,A,3,,...,3.563,52.626,0.674,1.0,50.61,,,N,NaN,615
7,ATOM,8,,CA,,PHE,,A,3,,...,4.261,51.413,1.102,1.0,48.73,,,C,NaN,616
8,ATOM,9,,C,,PHE,,A,3,,...,4.881,50.670,-0.064,1.0,48.17,,,C,NaN,617
9,ATOM,10,,O,,PHE,,A,3,,...,6.035,50.257,0.019,1.0,47.56,,,O,NaN,618
10,ATOM,11,,CB,,PHE,,A,3,,...,3.342,50.479,1.896,1.0,47.95,,,C,NaN,619
11,ATOM,12,,CG,,PHE,,A,3,,...,2.747,51.112,3.120,1.0,46.23,,,C,NaN,620
12,ATOM,13,,CD1,,PHE,,A,3,,...,3.425,52.100,3.804,1.0,43.75,,,C,NaN,621
13,ATOM,14,,CD2,,PHE,,A,3,,...,1.509,50.701,3.594,1.0,45.77,,,C,NaN,622
14,ATOM,15,,CE1,,PHE,,A,3,,...,2.893,52.679,4.942,1.0,44.62,,,C,NaN,623
15,ATOM,16,,CE2,,PHE,,A,3,,...,0.955,51.280,4.728,1.0,45.65,,,C,NaN,624
16,ATOM,17,,CZ,,PHE,,A,3,,...,1.655,52.273,5.409,1.0,45.91,,,C,NaN,625
17,ATOM,18,,N,,SER,,A,4,,...,4.122,50.518,-1.151,1.0,47.69,,,N,NaN,626
18,ATOM,19,,CA,,SER,,A,4,,...,4.593,49.745,-2.323,1.0,47.00,,,C,NaN,627
19,ATOM,20,,C,,SER,,A,4,,...,5.896,50.254,-2.977,1.0,45.29,,,C,NaN,628
20,ATOM,21,,O,,SER,,A,4,,...,6.627,49.479,-3.592,1.0,45.34,,,O,NaN,629
21,ATOM,22,,CB,,SER,,A,4,,...,3.489,49.633,-3.387,1.0,47.47,,,C,NaN,630
22,ATOM,23,,OG,,SER,,A,4,,...,3.169,50.916,-3.908,1.0,49.92,,,O,NaN,631
23,ATOM,24,,N,,ASN,,A,5,,...,6.184,51.544,-2.832,1.0,43.32,,,N,NaN,632
24,ATOM,25,,CA,,ASN,,A,5,,...,7.351,52.145,-3.480,1.0,41.42,,,C,NaN,633